//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Last
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CMV_TIPO_CUENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_CMV_TIPO_CUENTA()
        {
            this.TBL_CMV_CLIENTE_CUENTA = new HashSet<TBL_CMV_CLIENTE_CUENTA>();
        }
    
        public int idCuenta { get; set; }
        public string nombreCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CMV_CLIENTE_CUENTA> TBL_CMV_CLIENTE_CUENTA { get; set; }
    }
}
