//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Last
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CMV_CLIENTE_CUENTA
    {
        public int idClienteCuenta { get; set; }
        public int idCliente { get; set; }
        public int idCuenta { get; set; }
        public decimal saldoActual { get; set; }
        public System.DateTime fechaContratacion { get; set; }
        public System.DateTime fechaUltimoMovimiento { get; set; }
    
        public virtual CAT_CMV_TIPO_CUENTA CAT_CMV_TIPO_CUENTA { get; set; }
        public virtual TBL_CMV_CLIENTE TBL_CMV_CLIENTE { get; set; }
    }
}
